script(generate-depls): update secrets test data
To avoid interlopation error, and to use a recent stemcell.
Use 3468.1 instead of 3363.14 because the old version is not available in
our S3

error: could not resolve template vars: Invalid type 'float64' for value '3363.14' and variable 'stemcell-version'. Supported types for interpolation within a string are integers and strings.