pipeline(depls): fix rebase error on generated manifest auto update commit
Instead of updating secret-deployment (it is usually an outdated view),
we update secrets-full-writer (the latest view of secrets repo).

```
rebasing...
From xxxx
 * branch              master     -> FETCH_HEAD
 * [new branch]        master     -> push-target/master
error: could not apply 999aa999... yyy generated manifest auto update - [skip ci]
```

closes #85