chore(gem): bump to latest gem (rspec, simplecov, github_changelog_generator, ...) (#301)
* chore(gem): bump to latest gem (rspec, simplecov, github_changelog_generator, git, mdl, rake, reek, ...)

but we stick to  simplecov 0.16.1 to avoid code climate error:
```
DEBU[0000] couldn't load committed at from ENV, trying git...
Error: json: cannot unmarshal object into Go struct field input.coverage of type []formatters.NullInt
Usage:
  cc-test-reporter after-build [flags]
```