task(repackage_release): fix default value when `missing-s3-releases.yml` is empty
Error:
`repackage_releases.rb:147:in `missing_boshrelease?': undefined method `dig' for false:FalseClass (NoMethodError)`